name: Deploy Website via FTPS

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Нужно для отслеживания только измененных файлов

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
        # хостинги бегета - хуетища ебаная
          protocol: ftps
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: task/MyTravelNotes/site/
          # Исключаем служебные файлы и файлы с конфигами:
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            .gitignore
            **/.gitignore/**
            .env
            README.md